export const SETUP_SQL = `-- Manual SQL bootstrap has been retired.
-- Source of truth now lives in supabase/migrations.
-- Run the real migrations instead of pasting ad-hoc SQL from the UI.
--
-- Recommended flow:
--   1. Apply migrations from supabase/migrations
--   2. Deploy edge functions from supabase/functions
--   3. Set required secrets:
--      - SUPABASE_SERVICE_ROLE_KEY
--      - YOCO_SECRET_KEY
--      - YOCO_WEBHOOK_SECRET
--      - ALLOWED_ORIGIN
--
-- If this project is broken, do not patch production by copying SQL from a textarea.
-- Fix the migration set and redeploy cleanly.`;
